### ISSUE TITLE
リンクが効いていない

### ISSUE THREAD

**Issue by sottar** [t32k/webpagetest-doc-ja#1]
[using-webpagetest/index.md](https://github.com/t32k/webpagetest-doc-ja/blob/master/using-webpagetest/index.md) のリンクが効いていないです。

``` [] ``` の前にある tab を削除するとリンクになります。

**Comment by t32k** [comment]
https://github.com/t32k/webpagetest-doc-ja/commit/be51582f6bf8b61be5f17bb8802760c62305d13d
